[tool.ruff]
# Target non-EOL releases at minimum - https://devguide.python.org/versions/
target-version = "py39"
# Soft 80 and hard break at 120
line-length = 120

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'double'
docstring-quotes = 'double'

[tool.ruff.format]
quote-style = 'double'
indent-style = 'tab'
